### ISSUE TITLE
Telegram notification does not seem to be working

### ISSUE THREAD

**Issue by themarkymark-steem** [witness-essentials/watcher#1]
I am receiving this message although I know the token and bot name is correct and I have sent a memo to the bot to initiate a dialog.

`(node:31673) UnhandledPromiseRejectionWarning: Error: 400: Bad Request: chat not found`

**Comment by therealwolf42** [comment]
Resolved. `TELEGRAM > USER_ID` inside `config.json` is the user_id from the telegram account - not the account.
